<div id="menu-admin">
    <h2>Dashboard</h2>
    <p>Articles</p>
    <p>Utilisateurs</p>
    <p>Commentaires</p>
</div>

<section id="dashboard">

    <button></button>

    <div>
    <?php foreach($articles as $article): ?>
        <h2><?= $article['title'] ?></h2>
        <time> <?= $article['created_at'] ?></time>
        <br>
        <a href="delete.php?id=<?= $article['id']; ?>">Supprimer</a>
        <a href="update.php?id=<?= $article['id']; ?>">Modifier</a>
    <?php endforeach; ?>
    </div>

    <div>

    </div>
</section>

<section id ="admin-articles">
    <h3>Articles</h3>
    <?php foreach($articles as $article): ?>
        <h2><?= $article['title'] ?></h2>
        <time> <?= $article['created_at'] ?></time>
        <br>
        <a href="delete.php?id=<?= $article['id']; ?>">Supprimer</a>
        <a href="update.php?id=<?= $article['id']; ?>">Modifier</a>
    <?php endforeach; ?>
</section>

<section id ="admin-utilisateurs">
    <h3>Utilisateurs</h3>
    <?php foreach ($users as $user) : ?>
        <p><?= $user['username'] ?> <a href="banned.php?id=<?= $user['id']; ?>">Bannir</a></p>
    <?php endforeach; ?>
</section>

<section id ="admin-commentaires">
    <h3>Commentaires</h3>
    <?php foreach ($comments as $com) : ?>
        <h3><?= $com['author'] ?></h3>
        <time><?= $com['created_at'] ?></time>
        <p><?= $com['content'] ?></p>
    <?php endforeach; ?>
</section>




