<!-- Message flash le cas échéant -->
<?php if ($flashMessage != null) : ?>
    <p><?= $flashMessage; ?></p>
<?php endif; ?>

<section class="columns-container">
    <div class="wrapper">
        <div class="col-1">
            <div class="content-column">
                <?php foreach ($articles as $article) : ?>
                    <article class="standard-article">
                        <div class="img-article" style="background-image: url('<?= $article['image'] ?>')">
                            <div class="category-article">
                                <div>
                                    <img src=" <?= getCategoryIcon($article['id']) ?>" alt="">
                                    <a><?= getCategoryName($article['id']) ?></a>
                                </div>
                                <time><?= $article['created_at'] ?></time>
                            </div>
                        </div>

                        <div class="content-article">
                            <h2><?= $article['title'] ?></h2>
                            <p><?= $article['intro'] ?></p>
                            <span>
                                <p>by <?= getUserName($article['id']) ?></p>
                                <a href="article.php?id=<?= $article['id'] ?>">Lire la suite</a>
                            </span>
                        </div>
                    </article>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="col-2">
            <div class="content-column">
                <?php foreach ($articles as $article) : ?>
                    <article class="standard-article">
                        <div class="img-article" style="background-image: url('<?= $article['image'] ?>')">
                            <div class="category-article">
                                <div>
                                    <img src=" <?= getCategoryIcon($article['id']) ?>" alt="">
                                    <a><?= getCategoryName($article['id']) ?></a>
                                </div>
                                <time><?= $article['created_at'] ?></time>
                            </div>
                        </div>

                        <div class="content-article">
                            <h2><?= $article['title'] ?></h2>
                            <p><?= $article['intro'] ?></p>
                            <span>
                                <p>by <?= getUserName($article['id']) ?></p>
                                <a href="article.php?id=<?= $article['id'] ?>">Lire la suite</a>
                            </span>
                        </div>
                    </article>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <div id="right-block">
        <div id="quotes">
            <span>
                <h2>Sci-Fact du Jour</h2>
            </span>
            <p><?= getDayFact() ?></p>
        </div>

        <div id="top-article-box">
            <?php foreach ($topArticles as $topArticle) : ?>
                <article>
                    <div id="img-top" style="background-image: url('<?= $topArticle['image'] ?>')">
                    </div>

                    <h2><?= $topArticle['title'] ?></h2>
                    <p><?= $topArticle['intro'] ?></p>
                </article>
            <?php endforeach; ?>
        </div>
    </div>

</section>