    <div id="login-page">
        <h1>Connexion</h1>

        <?php if(!empty($error)) : ?>
            <p><?=$error;?></p>
        <?php endif; ?>

        <form action="login.php" method="POST">
            <label for="email">Email</label>
            <input type="text" name="email" id="email">
            <label for="password">Mot de Passe</label>
            <input type="password" name="password" id="password">
            <input type="submit" value="Connexion">
        </form>
    </div>
</body>
</html>