<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connexion</title>
</head>

<body>
    <div>
        <h1>Connexion</h1>

        <?php if(!empty($error)) : ?>
            <p><?=$error;?></p>
        <?php endif; ?>

        <form action="login.php" method="POST">
            <label for="email">Email</label>
            <input type="text" name="email" id="email">
            <label for="password">Mot de Passe</label>
            <input type="password" name="password" id="password">
            <input type="submit" value="Connexion">
        </form>
    </div>
</body>
</html>