<form class="form" enctype="multipart/form-data" action="<?= constructUrl('admin_article_new'); ?>" method="POST">
  <div class="form-group mb-3">
    <label for="title">Titre :</label>
    <input type="text" id="title" name="title" value="<?= $title; ?>" class="form-control">
    <?php if (isset($errors['title'])) : ?>
      <p class="error"><?= $errors['title']; ?></p>
    <?php endif; ?>
  </div>

  <div class="form-group mb-3">
    <label for="category">Catégorie :</label>
    <select name="category" id="category" class="form-control">
      <?php foreach ($categories as $category) : ?>
        <option value="<?= intval($category->getIdCategory()); ?>"><?= htmlspecialchars($category->getName()); ?></option>
      <?php endforeach; ?>
    </select>
  </div>

  <div class="form-group mb-3">
    <label for="summary">Résumé :</label>
    <input type="text" id="summary" name="summary" value="<?= $summary; ?>" class="form-control">
    <?php if (isset($errors['summary'])) : ?>
      <p class="error"><?= $errors['summary']; ?></p>
    <?php endif; ?>
  </div>

  <div class="form-group mb-3">
    <label for="content">Contenu :</label>
    <textarea id="content" name="content" class="form-control"><?= $content; ?></textarea>
    <?php if (isset($errors['content'])) : ?>
      <p class="error"><?= $errors['content']; ?></p>
    <?php endif; ?>
  </div>

  <div class="form-group mb-3">
    <label for="image">Image :</label>
    <input type="file" id="image" name="image" class="form-control-file">
    <?php if (isset($errors['image'])) : ?>
      <p class="error"><?= $errors['image']; ?></p>
    <?php endif; ?>
  </div>

  <input type="submit" value="Enregistrer" class="btn btn-primary">
</form>
