<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon super blog</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?=asset('css/base.css');?>" />
</head>
<body>
    <header>
        <nav>
            <a href="<?=constructUrl('home');?>">Accueil</a>
            <a href="<?=constructUrl('admin_dashboard');?>">Administration</a>
            <a href="<?=constructUrl('logout');?>">Déconnexion</a>
        </nav>
    </header>
    <main class="container-md">

        <!-- Message flash -->
        <?php if (isset($flashMessage) && $flashMessage): ?>
            <p class="success"><?=$flashMessage;?></p>
        <?php endif; ?>

        <!-- Contenu de la page -->
        <?php include TEMPLATE_DIR . '/admin/' . $template . '.phtml'; ?>
    </main>
</body>
</html>
