<div class="d-flex justify-content-between">
    <h2>Liste des articles</h2>
    <div class="d-flex">
        <a href="<?= constructUrl('admin_article_new'); ?>" class="btn btn-primary">Ajouter un article</a>
        <!-- Ajoutez une classe ou un style pour l'espace entre le titre et le bouton -->
        <div class="ml-2"></div>
    </div>
</div>


<div class="dashboard-content">
    <table class="table">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Catégorie</th>
                <th>Auteur</th>
                <th>Date de création</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($articles as $article): ?>
                <tr>
                    <td><?= $article->getTitle(); ?></td>
                    <td><?= $article->getCategoryName(); ?></td>
                    <td><?= $article->getUserName(); ?></td>
                    <td><?= $article->getFormattedCreatedAt(); ?></td>
                    <td>
                        <a href="<?= constructUrl('admin_article_edit', ['id' => $article->getIdArticle()]); ?>" class="btn btn-sm btn-primary">Modifier</a>
                        <form action="<?= constructUrl('admin_article_delete'); ?>" method="POST" style="display: inline;">
                          <input type="hidden" name="id" value="<?= $article->getIdArticle(); ?>">
                          <button type="submit" class="btn btn-sm btn-danger">Supprimer</button>
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>