<h1><?= $article->getTitle() ?></h1>
<time> <?= $article->getFormattedCreatedAt() ?></time>

<button class="btn-save" data-article-id="<?= $id ?>">Enregistrer</button>

<form action="article.php?id=<?= constructUrl('article', ['id' => $article->getIdArticle()]) ?>" method="POST">
    <label for="nickname">Pseudo :</label>
    <input type="text" name="nickname" id="nickname" value="<?php if (isset($nickname)) echo $author ?>">

    <label for="comment">Commentaire :</label>
    <textarea name="comment" id="comment" cols="30" rows="10"></textarea>
    <button type="submit">Envoyer</button>
</form>

<h2>Commentaires :</h2>

<?php foreach ($comments as $com) : ?>
    <h3><?= $com['nickname'] ?></h3>
    <time><?= $com['createdAt'] ?></time>
    <p><?= $com['content'] ?></p>
<?php endforeach; ?>