<h1><?= $article->getTitle() ?></h1>
<time> <?= $article->getFormattedCreatedAt() ?></time>

<button class="btn-save" data-article-id="<?= $article->getIdArticle() ?>">Enregistrer</button>

<form action="<?= constructUrl('article', ['id' => $article->getIdArticle()]) ?>" method="POST">
    <label for="nickname">Pseudo :</label>
    <input type="text" name="nickname" id="nickname" value="<?php if (isset($nickname)) echo $author ?>">

    <label for="content">Commentaire :</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <button type="submit">Envoyer</button>
</form>

<h2>Commentaires :</h2>

<?php foreach ($comments as $comment) : ?>
    <h3><?= $comment->getNickname() ?></h3>
    <time><?= $comment->getFormattedCreatedAt() ?></time>
    <p><?= $comment->getContent() ?></p>
<?php endforeach; ?>