<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Sci-Fi</title>
    <link rel="stylesheet" href="<?= asset("css/style.css") ?>">
    <script src="https://kit.fontawesome.com/76e1dcc4c0.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="<?= asset("js/home.js") ?>" defer></script>
    <script src="<?= asset("js/article.js") ?>" defer></script>
    <script src="<?= asset("js/admin.js") ?>" defer></script>
</head>

<body>
    <header>
        <h1>Mon super Blog</h1>
    </header>

        <nav>
            <a href="<?=constructUrl('home');?>">Accueil</a>
            <a href="<?=constructUrl('contact-form');?>">Contact</a>
            <?php if ((new App\Service\UserSession())->getUser()):?>
                <a href="<?=constructUrl('logout');?>">Déconnexion</a>
            <?php else: ?>
                <a href="<?=constructUrl('login');?>">Connexion</a>
                <a href="<?=constructUrl('signup');?>">Créer un compte</a>
            <?php endif; ?>
        </nav>

    <main>

        <!-- Message flash -->
        <?php if (isset($flashMessage) && $flashMessage): ?>
            <p class="success"><?=$flashMessage;?></p>
        <?php endif; ?>

        <!-- Contenu de la page -->
        <?php include TEMPLATE_DIR . '/' . $template . '.phtml'; ?>
    </main>
</body>
</html>