<section class="columns-container">
    <div class="wrapper">
        <div class="col-1">
            <div class="content-column">
                <?php foreach ($articles as $article) : ?>
                    <article class="standard-article">
                        <div class="img-article" style="background-image: url('<?= asset('images/' . $article->getImage()) ?>')">
                            <div class="category-article">
                                <div>
                                    <img src=" <?= asset('images/' . $article->getCategoryIcon()) ?>" alt="">
                                    <a><?= $article->getCategoryName() ?></a>
                                </div>
                                <time><?= $article->getFormattedCreatedAt(); ?></time>
                            </div>
                        </div>

                        <div class="content-article">
                            <h2><?= $article->getTitle(); ?></h2>
                            <p><?= $article->getSummary(); ?></p>
                            <span>
                                <p>by <?= $article->getUserName() ?></p>
                                <a href="<?= constructUrl('article', ['id' => $article->getIdArticle()]); ?>">Lire la suite</a>
                            </span>
                        </div>
                    </article>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="col-1">
            <div class="content-column">
                <?php foreach ($articles as $article) : ?>
                    <article class="standard-article">
                        <div class="img-article" style="background-image: url('<?= asset('images/' . $article->getImage()) ?>')">
                            <div class="category-article">
                                <div>
                                    <img src=" <?= asset('images/' . $article->getCategoryIcon()) ?>" alt="">
                                    <a><?= $article->getCategoryName() ?></a>
                                </div>
                                <time><?= $article->getFormattedCreatedAt(); ?></time>
                            </div>
                        </div>

                        <div class="content-article">
                            <h2><?= $article->getTitle(); ?></h2>
                            <p><?= $article->getSummary(); ?></p>
                            <span>
                                <p>by <?= $article->getUserName() ?></p>
                                <a href="<?= constructUrl('article', ['id' => $article->getIdArticle()]); ?>">Lire la suite</a>
                            </span>
                        </div>
                    </article>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <div id="right-block">
        <div id="quotes">
            <span>
                <h2>Sci-Fact du Jour</h2>
            </span>
            <p></p>
        </div>

        <div id="top-article-box">
            <h2>Top Articles</h2>
            <div class="top-article-container">
                <?php foreach ($topArticles as $topArticle) : ?>
                    <article class="top-article">
                        <div class="top-article-image" style="background-image: url('<?= asset('images/' . $topArticle->getImage()) ?>')">
                        </div>
                        <div class="top-article-details">
                            <h3><?= $topArticle->getTitle(); ?></h3>
                            <p><?= $topArticle->getSummary(); ?></p>
                            <a href="<?= constructUrl('article', ['id' => $topArticle->getIdArticle()]); ?>">Lire la suite</a>
                        </div>
                    </article>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

</section>

<script src="<?= asset("js/home.js") ?>"></script>